version: '3'

services: 
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=zx_code_challenge
      - MYSQL_USER=ze_delivery
      - MYSQL_PASSWORD=ZeDelivery@2018
  
  spring-boot-app:
    image: rollorafael/zxchallenge:latest
    depends_on:
      - db
    ports:
      - 8080:8080
    restart: on-failure
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=zx_code_challenge
      - DATABASE_USER=ze_delivery
      - DATABASE_PASSWORD=ZeDelivery@2018
      - SPRING_PROFILES_ACTIVE=prod
